package co.gov.dian.muisca.diligenciamientomasivo.general.constantes;

public interface IDConstantesDocTareaJuegosSuerteYAzar {
	 	int ANIO = 1;
	    int NUMERO_FORMULARIO = 4;
	    int TIPO_DOCUMENTO_REMITENTE = 20;
	    int NUMERO_IDENTIFICACION_REMITENTE = 18;
	    int DV_REMITENTE = 6;
	    int PRIMER_APELLIDO_REMITENTE = 7;
	    int SEGUNDO_APELLIDO_REMITENTE = 8;
	    int PRIMER_NOMBRE_REMITENTE = 9;
	    int OTROS_NOMBRES_REMITENTE = 10;
	    int RAZON_SOCIAL_REMITENTE = 11;
	    int TIPO_DOCUMENTO_INTERESADO = 24;
	    int NUMERO_IDENTIFICACION_INTERESADO = 25;
	    int DV_INTERESADO = 26;
	    int PRIMER_APELLIDO_INTERESADO = 27;
	    int SEGUNDO_APELLIDO_INTERESADO = 28;
	    int PRIMER_NOMBRE_INTERESADO = 29;
	    int OTROS_NOMBRES_INTERESADO = 30;
	    int RAZON_SOCIAL_INTERESADO = 31;    
	    int NUMERO_SOLICITUD = 32;
	    int ESTADO_SOLICITUD = 33;
	    int FORMATO_SOLICITUD = 34;
	    int VERSION_SOLICITUD = 35;
	    int CONCEPTO_SOLICITUD = 36;
	    int ANIO_VIGENCIA_SOLICITUD = 37;
	    int FECHA_SOLICITUD = 38;
	    int NUMERO_ARCHIVO_SOLICITUD = 39;
	    int NUMERO_REGISTROS_SOLICITUD = 40;
	    int NUMERO_FORMULARIO_PRESENTAR = 41;
	    int FORMATO_PRESENTAR = 42;
	    int VERSION_PRESENTAR = 43;
	    int TOTAL_BASE_LIQUIDACION = 44;
	    int TOTAL_DERECHOS_EXPLOTACION = 45;
	    int TOTAL_PAGAR_PERIODO = 46;
	    int TOTAL_A_PAGAR = 47;
	   
	    int APELLIDOS_NOMBERS = 984;
	    int CARGO = 985;
	    int OPERACION_AUTOMATICA = 1000;
	    int DEPENDENCIA = 989;
	    int ESTABLECIMIENTO = 993;
	    int AREA = 992;
	    int LUGAR_ADMINISTRATIVO = 990;
	    int ORGANIZACION = 991;
	    int FECHA_EXPEDICION = 997;
}
