package co.gov.dian.muisca.diligenciamientomasivo.general.preciostransferencia;

/**
 * <p>Title: </p>
 *
 * <p>Description: </p>
 *
 * <p>Copyright: Copyright (c) 2005</p>
 *
 * <p>Company: </p>
 *
 * @author not attributable
 * @version 1.0
 */
public interface IDConstantesFlujoPreciosTransferencia {

	//Flujo Precios de Transferencia
	String IDE_FLUJO_PRECIOS_TRANFERENCIA = "8a7f9e97158c371801158ff4c5d80005";
	String NOM_PARAM_TIPO_TRANSFERENCIA = "tipoTransferencia";
	String IDE_PARAM_TIPO_TRANSFERENCIA = "3CA4A2F5097B80A2E043C0A8FF9280A2";
	String NOM_PARAM_NUM_DOCU = "numeroDocumento";
	String IDE_PARAM_NUM_DOCU = "3CA4A2F5097D80A2E043C0A8FF9280A2";

	/*ACTIVIDAD PRESENTAR INFORMACION POR ENVIO DE ARCHIVOS*/
	String IDE_ACTIVIDAD_PRESENTACION_INFORMACION = "953f32730aff1e800107f1016fcb4079";
	//Tipos de Documento
	long IDE_DOC_SOLICITUD = 171;
	//Parametros
	String IDE_PAR_FORMATO_DOC_SOLICITUD = "3CB4A99737C2C178E043C0A8FF92C178";
	String NOM_PAR_FORMATO_DOC_SOLICITUD = "formato";
	String IDE_PAR_NOM_FORMATO_DOC_SOLICITUD = "3CB4A99737CbC178E043C0A8FF92C178";
	String NOM_PAR_NOM_FORMATO_DOC_SOLICITUD = "nomFormato";
	String IDE_PAR_VERSION_DOC_SOLICITUD = "3CB4A99737C4C178E043C0A8FF92C178";
	String NOM_PAR_VERSION_DOC_SOLICITUD = "version";
	String IDE_PAR_VIGENCIA_DOC_SOLICITUD = "3CB4A99737C6C178E043C0A8FF92C178";
	String NOM_PAR_VIGENCIA_DOC_SOLICITUD = "vigencia";
	String IDE_PAR_IDE_DOC_SOLICITUD = "3CB4A99737CAC178E043C0A8FF92C178";
	String NOM_PAR_IDE_DOC_SOLICITUD = "idDocumento";
	String IDE_PAR_IDE_TIPO_DECLARACION = "3D16E4DBC965A064E043C0A8FF92A064";
	String NOM_PAR_IDE_TIPO_DECLARACION = "tipoDeclaracion";

	/*ACTIVIDAD INFORMAR INCONSISTENCIA*/
	String IDE_ACTIVIDAD_INFORMAR_INCONSISTENCIA = "953f32e00aff1e8000cbf8b730d63d32";
	//Tipos de Documento
	long IDE_DOC_CARGA_MASIVA = 175;
	//Parametros
	String IDE_PAR_FORMATO_DOC_SOLICITUD_INCONSISTENCIA = "3D16E4DBC95BA064E043C0A8FF92A064";
	String NOM_PAR_FORMATO_DOC_SOLICITUD_INCONSISTENCIA = "formato";
	String IDE_PAR_NOM_FORMATO_DOC_SOLICITUD_INCONSISTENCIA = "3D16E4DBC968A064E043C0A8FF92A064";
	String NOM_PAR_NOM_FORMATO_DOC_SOLICITUD_INCONSISTENCIA = "nomFormato";
	String IDE_PAR_VERSION_DOC_SOLICITUD_INCONSISTENCIA = "3D16E4DBC95DA064E043C0A8FF92A064";
	String NOM_PAR_VERSION_DOC_SOLICITUD_INCONSISTENCIA = "version";
	String IDE_PAR_VIGENCIA_DOC_SOLICITUD_INCONSISTENCIA = "3D16E4DBC95FA064E043C0A8FF92A064";
	String NOM_PAR_VIGENCIA_DOC_SOLICITUD_INCONSISTENCIA = "vigencia";
	String IDE_PAR_IDE_DOC_SOLICITUD_INCONSISTENCIA = "3D16E4DBC963A064E043C0A8FF92A064";
	String NOM_PAR_IDE_DOC_SOLICITUD_INCONSISTENCIA = "idDocumento";
	String IDE_PAR_IDE_TIPO_DECLARACION_INCONSISTENCIA = "3D16E4DBC965A064E043C0A8FF92A064";
	String NOM_PAR_IDE_TIPO_DECLARACION_INCONSISTENCIA = "tipoDeclaracion";
	String IDE_PAR_IDE_TIPO_ERROR_INCONSISTENCIA = "3D16E4DBC967A064E043C0A8FF92A064";
	String NOM_PAR_IDE_TIPO_ERROR_INCONSISTENCIA = "tipoError";

	/*ACTIVIDAD PRESENTAR DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUALES*/
	String IDE_ACTIVIDAD_SOLICITUD_DILIGENCIAMIENTO_INDIVIDUALES = "953f32b10aff1e80015e1d40d980bc5e";
	//Tipos de Documento
	long IDE_DOC_INDIVIDUAL = 173;
	//Parametros
	String IDE_PAR_FORMATO_DOC_INDIVIDUAL = "3D16E4DBC9A7A064E043C0A8FF92A064";
	String NOM_PAR_FORMATO_DOC_INDIVIDUAL = "formato";
	String IDE_PAR_NOM_FORMATO_DOC_INDIVIDUAL = "3D16E4DBC9ACA064E043C0A8FF92A064";
	String NOM_PAR_NOM_FORMATO_DOC_INDIVIDUAL = "nomFormato";
	String IDE_PAR_VERSION_DOC_INDIVIDUAL = "3D16E4DBC9A9A064E043C0A8FF92A064";
	String NOM_PAR_VERSION_DOC_INDIVIDUAL = "version";
	String IDE_PAR_IDE_DOC_INDIVIDUAL = "3D16E4DBC9ABA064E043C0A8FF92A064";
	String NOM_PAR_IDE_DOC_INDIVIDUAL = "idDocumento";


	/*ACTIVIDAD PRESENTAR DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA
   CONSOLIDADA*/
	String IDE_ACTIVIDAD_SOLICITUD_DILIGENCIAMIENTO_CONSOLIDADA = "953f32c10aff1e8001d4633628bfa715";
	//Tipos de Documento
	long IDE_DOC_CONSOLIDADA = 172;
	//Parametros
	String IDE_PAR_FORMATO_DOC_CONSOLIDADA = "3D58A9D197F7612EE043C0A8FF92612E";
	String NOM_PAR_FORMATO_DOC_CONSOLIDADA = "formato";
	String IDE_PAR_NOM_FORMATO_DOC_CONSOLIDADA = "3D58A9D197FC612EE043C0A8FF92612E";
	String NOM_PAR_NOM_FORMATO_DOC_CONSOLIDADA = "nomFormato";
	String IDE_PAR_VERSION_DOC_CONSOLIDADA = "3D58A9D197F9612EE043C0A8FF92612E";
	String NOM_PAR_VERSION_DOC_CONSOLIDADA = "version";
	String IDE_PAR_IDE_DOC_CONSOLIDADA = "3D58A9D197FB612EE043C0A8FF92612E";
	String NOM_PAR_IDE_DOC_CONSOLIDADA = "idDocumento";

	/*ACTIVIDAD CANCELAR EXPEDIENTE POR VENCIMIENTO DE TAREA*/
	String IDE_ACTIVIDAD_CANCELAR_POR_VENCIMIENTO_TAREA = "3dcc558c0d1431a2e043c0a8ff9231a2";
	//Tipos de Documento
	long IDE_DOC_TAREA = 197;
	//Parametros
	String IDE_PAR_EXPEDIENTE_CANCELACION = "3dcc558c0d1631a2e043c0a8ff9231a2";
	String NOM_PAR_EXPEDIENTE_CANCELACION = "idExpediente";
	String IDE_PAR_IDE_DOC_TAREA_VENCIDA = "3dcc558c0d1831a2e043c0a8ff9231a2";
	String NOM_PAR_IDE_DOC_TAREA_VENCIDA = "idDocTarea";
	String IDE_PAR_NUM_REPET_DOC_TAREA_VENCIDA = "3dcc558c0d1a31a2e043c0a8ff9231a2";
	String NOM_PAR_NUM_REPET_DOC_TAREA_VENCIDA = "numRepDocTarea";


	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 6*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V6 = 56;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V6 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V6 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V6 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V6 = 4;

	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 7*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V7 = 36;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V7 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V7 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V7 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V7 = 4;

	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 8*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V8 = 54;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V8 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V8 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V8 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V8 = 4;

	/*
	 * TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 9
	 */
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V9 = 129;
	// Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V9 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V9 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V9 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V9 = 4;

	/*
	 * TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 1
	 */
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V1 = 239;
	// Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V1 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V1 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V1 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V1 = 4;

	/*
	 * TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 2
	 */
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V2 = 744;
	// Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V2 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V2 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V2 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V2 = 4;

	/*
	 * TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 3
	 */
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V3 = 1048;
	// Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V3 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V3 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V3 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V3 = 4;	

	/*
	 * TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 4
	 */
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V4 = 1261;
	// Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V4 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V4 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V4 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V4 = 4;	

	/*
	 * TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 5
	 */
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V5 = 1381;
	// Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL_V5 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL_V5 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL_V5 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL_V5 = 4;	
	
	/*
	 * TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA INDIVIDUAL VERSION 10
	 */
	long IDE_TAREA_DILIGENCIAR_DECLARACION_INDIVIDUAL_V10 = 1441;
	// Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_INDIVIDUAL = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_INDIVIDUAL = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_INDIVIDUAL = 3;
	int IDE_PAR_TAREA_ES_REPETICION_INDIVIDUAL = 4;


	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA CONSOLIDADA VERSION 7*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_CONSOLIDADA_V7 = 37;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_CONSOLIDADA_V7 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_CONSOLIDADA_V7 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_CONSOLIDADA_V7 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_CONSOLIDADA_V7 = 4;

	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA CONSOLIDADA VERSION 8*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_CONSOLIDADA_V8 = 230;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_CONSOLIDADA_V8 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_CONSOLIDADA_V8 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_CONSOLIDADA_V8 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_CONSOLIDADA_V8 = 4;
	
	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA CONSOLIDADA VERSION 9*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_CONSOLIDADA_V9 = 774;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_CONSOLIDADA_V9 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_CONSOLIDADA_V9 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_CONSOLIDADA_V9 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_CONSOLIDADA_V9 = 4;
	
	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA CONSOLIDADA VERSION 1*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_CONSOLIDADA_V1 = 1049;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_CONSOLIDADA_V1 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_CONSOLIDADA_V1 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_CONSOLIDADA_V1 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_CONSOLIDADA_V1 = 4;
	
	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA CONSOLIDADA VERSION 2*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_CONSOLIDADA_V2 = 1291;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_CONSOLIDADA_V2 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_CONSOLIDADA_V2 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_CONSOLIDADA_V2 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_CONSOLIDADA_V2 = 4;

	/*TAREA DILIGENCIAR DOCUMENTO DECLARACION INFORMATIVA DE PRECIOS DE TRANSFERENCIA CONSOLIDADA VERSION 7*/
	long IDE_TAREA_DILIGENCIAR_DECLARACION_CONSOLIDADA_V6 = 55;
	//Parametros
	int IDE_PAR_TAREA_DOC_DECLARACION_CONSOLIDADA_V6 = 1;
	int IDE_PAR_TAREA_NUM_REP_DOC_DECLARACION_CONSOLIDADA_V6 = 2;
	int IDE_PAR_TAREA_DOC_SOLICITUD_CONSOLIDADA_V6 = 3;
	int IDE_PAR_TAREA_ES_REPETICION_CONSOLIDADA_V6 = 4;

}
